## VISTAS ##
cliente_view_listacliente:
    path:     /lista-cliente/
    defaults: { _controller: ClienteBundle:ListaCliente:listaCliente }

## FUNCIONES AJAX ##
cliente_ajax_validarrutcliente:
    path:     /validar-rut-cliente/
    defaults: { _controller: ClienteBundle:FnFormulario:validarRutCliente }
    options:
        expose: true

cliente_ajax_clienteporid:
    path:     /obtener-cliente/
    defaults: { _controller: ClienteBundle:FnFormulario:obtenerClientePorId }
    options:
        expose: true

cliente_ajax_cargarlista:
    path:     /lista-cliente/cargar-lista/
    defaults: { _controller: ClienteBundle:ListaCliente:cargarLista }
    options:
        expose: true
