sucursal:
    resource: "@SucursalBundle/Resources/config/routing.yml"
    prefix:   /sucursal/

bodega:
    resource: "@BodegaBundle/Resources/config/routing.yml"
    prefix:   /bodega/

mantenciones:
    resource: "@MantencionBundle/Resources/config/routing.yml"
    prefix:   /mantencion/

cliente:
    resource: "@ClienteBundle/Resources/config/routing.yml"
    prefix:   /Cliente/
    
venta:
    resource: "@VentaBundle/Resources/config/routing.yml"
    prefix:   /venta/

plugin:
    resource: "@PluginBundle/Resources/config/routing.yml"
    prefix:   /plugin/

usuario:
    resource: "@UsuarioBundle/Resources/config/routing.yml"
    prefix:   /usuario/

base:
    resource: "@BaseBundle/Resources/config/routing.yml"
    prefix:   /

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

EndroidQrCodeBundle:
    resource: "@EndroidQrCodeBundle/Controller/"
    type:     annotation
    prefix:   /qrcode