## VISTAS ##
venta_vista_inicio:
    path:     /inicio/
    defaults: { _controller: VentaBundle:Inicio:inicio }

venta_vista_ventaservicio:
    path:     /nueva-venta-servicio/
    defaults: { _controller: VentaBundle:VentaServicio:nuevaVenta }

venta_vista_listaventa:
    path:     /lista-venta/
    defaults: { _controller: VentaBundle:ListaVenta:lista }

venta_vista_verventa:
    path:     /ver/{id}
    defaults: { _controller: VentaBundle:VerVenta:ver, id: 0 }
    options:
        expose: true

venta_vista_completarventa:
    path:     /completar/{id}
    defaults: { _controller: VentaBundle:CompletarVenta:inicio, id: 1 }

venta_exportar_imprimircontrato:
    path:     /imprimir-contrato/{id}
    defaults: { _controller: VentaBundle:VerVenta:contratoPdf, id: 0 }
    
## METODOS SIN VISTA ##
venta_vista_guardarventa:
    path:     /nueva-venta-servicio/guardar-venta/
    defaults: { _controller: VentaBundle:VentaServicio:guardarVenta }
    methods:   [POST]

venta_vista_exportarlistaclientes:
    path:     /lista-venta/exportar-lista-excel/
    defaults: { _controller: VentaBundle:ListaVenta:exportarListaClienteExcel }

## FUNCIONES AJAX ##
venta_ajax_crearventa:
    path:     /nueva-venta-servicio/crear-venta/
    defaults: { _controller: VentaBundle:VentaServicio:crearVenta }
    options:
        expose: true

venta_ajax_cargarlistaventaservicio:
    path:     /lista-venta/cargar-lista-venta-servicio/
    defaults: { _controller: VentaBundle:ListaVenta:cargarLista }
    options:
        expose: true

venta_ajax_verdetallemantencion:
    path:     /ver/detalle-mantencion/
    defaults: { _controller: VentaBundle:VerVenta:detalleMantencion }
    options:
        expose: true

venta_ajax_finalizararriendo:
    path:     /lista-venta/finalizar-venta/
    defaults: { _controller: VentaBundle:ListaVenta:finalizarVenta }
    options:
        expose: true

venta_ajax_guardardetalleventa:
    path:     /ver/guardar-detalle-venta/
    defaults: { _controller: VentaBundle:VerVenta:guardarDetalleVenta }
    options:
        expose: true

venta_ajax_guardarnombrecliente:
    path:     /ver/guardar-nombre-cliente/
    defaults: { _controller: VentaBundle:VerVenta:guardarNombreCliente }
    options:
        expose: true

venta_ajax_crearnuevodetalle:
    path:     /ver/crear-detalle-arriendo/
    defaults: { _controller: VentaBundle:VerVenta:crearDetalleArriendo }
    options:
        expose: true

venta_ajax_cargarcomunas:
    path:     /ver/cargar-comunas/
    defaults: { _controller: VentaBundle:VerVenta:cargarComunas }
    options:
        expose: true

venta_ajax_eliminardetalle:
    path:     /ver/eliminar-detalle/
    defaults: { _controller: VentaBundle:VerVenta:eliminarDetalle }
    options:
        expose: true